name: Daily Spreadsheet Crawl & Raid Check
on:
  # schedule:
  #   # 00:00 (자정)
  #   - cron: '0 15 * * *'
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  crawl-and-raid-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, zip, intl, sqlite3
          coverage: none

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Install NPM dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Create .env file
        run: |
          cat > .env << 'EOF'
          APP_ENV=production
          APP_DEBUG=false
          APP_KEY=${{ secrets.APP_KEY }}
          GOOGLE_SPREADSHEET_ID=${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON='${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}'
          DFO_API_KEY=${{ secrets.DFO_API_KEY }}
          DFO_API_BASE_URL=${{ secrets.DFO_API_BASE_URL }}
          DFO_API_VERSION=${{ secrets.DFO_API_VERSION }}
          CRAWLER_TIMEOUT=${{ secrets.CRAWLER_TIMEOUT }}
          CRAWLER_RETRIES=${{ secrets.CRAWLER_RETRIES }}
          CRAWLER_DELAY=${{ secrets.CRAWLER_DELAY }}
          GOOGLE_APPLICATION_NAME="Spreadsheet Crawler"
          CRAWLER_MIN_HTML_SIZE=760000
          EOF

      - name: Create Google service account file
        run: |
          mkdir -p storage/app/google
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > storage/app/google/service-account.json

      - name: Debug environment variables
        run: |
          echo "Checking if GOOGLE_SERVICE_ACCOUNT_JSON is set..."
          if [ -n "$GOOGLE_SERVICE_ACCOUNT_JSON" ]; then
            echo "✅ GOOGLE_SERVICE_ACCOUNT_JSON environment variable is set"
            echo "First 50 characters: ${GOOGLE_SERVICE_ACCOUNT_JSON:0:50}..."
          else
            echo "❌ GOOGLE_SERVICE_ACCOUNT_JSON environment variable is NOT set"
          fi

          echo "Checking service account file..."
          if [ -f "storage/app/google/service-account.json" ]; then
            echo "✅ Service account file exists"
            echo "File size: $(wc -c < storage/app/google/service-account.json) bytes"
          else
            echo "❌ Service account file does NOT exist"
          fi

      - name: Generate application key
        run: php artisan key:generate --ansi

      - name: Clear and cache config
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: Run spreadsheet crawling
        run: php artisan crawl:sheets

      - name: Wait between operations
        run: sleep 10

      - name: Run raid status check
        run: |
          echo "=== 레이드 체크 시작 ==="
          echo "현재 시간: $(date)"
          echo "타임존: $(timedatectl show --property=Timezone --value 2>/dev/null || echo 'N/A')"
          echo "환경변수 체크:"
          echo "- NEOPLE_API_KEY 설정됨: $([ -n "$NEOPLE_API_KEY" ] && echo 'YES' || echo 'NO')"
          echo "========================"
          php artisan raid:check -v

      - name: Upload logs (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crawl-logs-${{ github.run_number }}
          path: storage/logs/
          retention-days: 7
